<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class Student extends Model
{
    use HasSlug;

    protected $fillable = [
        'username',
        'full_name',
        'school_year_id',
        'exam_number',
    ];

    public function getSlugOptions(): SlugOptions
    {
        // TODO: Implement getSlugOptions() method.
        return SlugOptions::create()
            ->generateSlugsFrom('full_name')
            ->saveSlugsTo('username');
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Student $student) {
            $student->school_year_id = SchoolYear::active()->first()->id;
        });
    }
}
