<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Attributes\Scope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;

class TestScore extends Model
{
    protected $fillable = [
        'slug',
        'school_year_id',
        'student_id',
        'total_score',
        'avg_score',
        'rank',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (TestScore $testScore) {
            $testScore->slug = Str::uuid()->toString();
        });
    }

    public function testScoreDetails(): HasMany
    {
        return $this->hasMany(TestScoreDetail::class, 'test_score_id');
    }

    // TODO Scope
    #[Scope]
    protected function schoolYearId(Builder $query, $schoolYearId): Builder
    {
        return $query->where('school_year_id', $schoolYearId);
    }

    #[Scope]
    protected function filterData(Builder $query, $filter): Builder
    {
        return $query->where([
            'school_year_id' => $filter['school_year_id'],
            'student_id' => $filter['student_id']
        ]);
    }
}
